/* Strings introduced by the 0.80 overhaul, in every language. Merged into
   i18n.js DICT (es/en at import, pt/fr/de with the lazy extra pack). */
export const STRINGS = {
  es: {
    "w.system": "Sistema",
    "w.focus": "Enfoque",
    "widget.systemDesc": "CPU, memoria, disco y red en una sola placa. Elige qué mostrar.",
    "widget.focusDesc": "Temporizador y lista de tareas, guardados solo en tu PC.",
    "focus.allDone": "Todo listo",
    "finish.title": "Acabado",
    "finish.glass": "Vidrio",
    "finish.glassHint": "Desenfoca lo que hay detrás",
    "finish.darkGlass": "Vidrio oscuro",
    "finish.darkGlassHint": "Como la barra de tareas",
    "finish.mica": "Mica",
    "finish.micaHint": "Opaco, teñido por tu fondo",
    "finish.solid": "Sólido",
    "finish.solidHint": "Sin transparencia",
    "tint.black": "Negro",
    "tint.graphite": "Grafito",
    "tint.slate": "Pizarra",
    "tint.night": "Azul noche",
    "tint.white": "Blanco",
  },
  en: {
    "w.system": "System",
    "w.focus": "Focus",
    "widget.systemDesc": "CPU, memory, disk and network on one plate. Choose what it shows.",
    "widget.focusDesc": "A timer and a task list, kept only on your PC.",
    "focus.allDone": "All done",
    "finish.title": "Finish",
    "finish.glass": "Glass",
    "finish.glassHint": "Blurs what is behind",
    "finish.darkGlass": "Dark glass",
    "finish.darkGlassHint": "Like the taskbar",
    "finish.mica": "Mica",
    "finish.micaHint": "Opaque, tinted by your wallpaper",
    "finish.solid": "Solid",
    "finish.solidHint": "No transparency",
    "tint.black": "Black",
    "tint.graphite": "Graphite",
    "tint.slate": "Slate",
    "tint.night": "Night blue",
    "tint.white": "White",
  },
  pt: {
    "w.system": "Sistema",
    "w.focus": "Foco",
    "widget.systemDesc": "CPU, memória, disco e rede numa só placa. Escolha o que mostrar.",
    "widget.focusDesc": "Um temporizador e uma lista de tarefas, guardados só no seu PC.",
    "focus.allDone": "Tudo feito",
    "finish.title": "Acabamento",
    "finish.glass": "Vidro",
    "finish.glassHint": "Desfoca o que está atrás",
    "finish.darkGlass": "Vidro escuro",
    "finish.darkGlassHint": "Como a barra de tarefas",
    "finish.mica": "Mica",
    "finish.micaHint": "Opaco, tingido pelo seu papel de parede",
    "finish.solid": "Sólido",
    "finish.solidHint": "Sem transparência",
    "tint.black": "Preto",
    "tint.graphite": "Grafite",
    "tint.slate": "Ardósia",
    "tint.night": "Azul-noite",
    "tint.white": "Branco",
  },
  fr: {
    "w.system": "Système",
    "w.focus": "Concentration",
    "widget.systemDesc": "Processeur, mémoire, disque et réseau sur une seule plaque. Choisissez quoi afficher.",
    "widget.focusDesc": "Un minuteur et une liste de tâches, gardés uniquement sur votre PC.",
    "focus.allDone": "Tout est fait",
    "finish.title": "Finition",
    "finish.glass": "Verre",
    "finish.glassHint": "Floute ce qui est derrière",
    "finish.darkGlass": "Verre sombre",
    "finish.darkGlassHint": "Comme la barre des tâches",
    "finish.mica": "Mica",
    "finish.micaHint": "Opaque, teinté par votre fond d’écran",
    "finish.solid": "Opaque",
    "finish.solidHint": "Sans transparence",
    "tint.black": "Noir",
    "tint.graphite": "Graphite",
    "tint.slate": "Ardoise",
    "tint.night": "Bleu nuit",
    "tint.white": "Blanc",
  },
  de: {
    "w.system": "System",
    "w.focus": "Fokus",
    "widget.systemDesc": "CPU, Arbeitsspeicher, Datenträger und Netzwerk auf einer Kachel. Wähle, was sie zeigt.",
    "widget.focusDesc": "Ein Timer und eine Aufgabenliste, nur auf deinem PC gespeichert.",
    "focus.allDone": "Alles erledigt",
    "finish.title": "Oberfläche",
    "finish.glass": "Glas",
    "finish.glassHint": "Macht den Hintergrund unscharf",
    "finish.darkGlass": "Dunkles Glas",
    "finish.darkGlassHint": "Wie die Taskleiste",
    "finish.mica": "Mica",
    "finish.micaHint": "Deckend, vom Hintergrundbild getönt",
    "finish.solid": "Deckend",
    "finish.solidHint": "Keine Transparenz",
    "tint.black": "Schwarz",
    "tint.graphite": "Graphit",
    "tint.slate": "Schiefer",
    "tint.night": "Nachtblau",
    "tint.white": "Weiß",
  },
};
