/* Strings introduced by the 0.80 overhaul, in every language. Merged into
   i18n.js DICT (es/en at import, pt/fr/de with the lazy extra pack). */
export const STRINGS = {
  es: {
    "home.atGlance": "De un vistazo",
    "release81.headline": "Ajustes rediseñado, una isla de notch que sí informa y grupos con color e icono.",
    "release81.settings": "Inicio con tu dock sobre un escritorio y un resumen de un vistazo. Cada sección tiene iconos, jerarquía clara y una vista previa del dock.",
    "release81.apps": "Apps y carpetas, rehecha: el dock se edita en una cuadrícula ordenada y la biblioteca va por pestañas con iconos grandes.",
    "release81.groups": "Los grupos pueden llevar un color de una paleta cuidada y un icono de la librería, en el dock y en Ajustes.",
    "release81.notch": "Nuevo notch Isla: un punto discreto que se abre en cápsula con el temporizador, la música o la batería baja.",
    "group.look": "Aspecto",
    "group.color": "Color",
    "group.icon": "Icono",
    "group.iconHint": "Un icono sustituye la cuadrícula de apps",
    "group.auto": "Automático",
    "apps.inDock": "En tu dock",
    "apps.widgetsElsewhere": "Los widgets se ordenan en la sección Widgets",
    "apps.addTitle": "Añadir al dock",
    "apps.tabApps": "Apps",
    "apps.tabFolders": "Carpetas",
    "apps.more": "Más",
    "color.blue": "Azul",
    "color.purple": "Morado",
    "color.pink": "Rosa",
    "color.red": "Rojo",
    "color.orange": "Naranja",
    "color.yellow": "Amarillo",
    "color.green": "Verde",
    "color.teal": "Turquesa",
    "color.graphite": "Grafito",
    "color.indigo": "Índigo",
    "color.sand": "Arena",
    "notch.batteryLow": "Batería baja · conecta el cargador",
    "be.notchModeSmart": "Isla",
    "be.notchModeSmartHint": "Un punto discreto que se convierte en cápsula con el temporizador, la música o la batería baja.",
    "release80.headline": "Booki, rehecho de arriba abajo: más simple, más claro y nativo de Windows 11.",
    "release80.settingsTitle": "Ajustes",
    "release80.settings": "Cinco secciones en lugar de nueve, con el estilo de Configuración de Windows 11 y Mica. La vista previa del dock ya no tiene barras de desplazamiento internas.",
    "release80.finishTitle": "Acabados",
    "release80.finish": "Vidrio, Mica y Sólido se ven realmente distintos. El desenfoque ya no asoma como un cuadro detrás de las esquinas redondeadas, y los widgets siguen el acabado.",
    "release80.widgetsTitle": "Widgets",
    "release80.widgets": "Diez widgets: Sistema reúne CPU, memoria, disco y red; Enfoque reúne temporizador y tareas. Tus widgets se convierten solos y conservan sus datos.",
    "release80.notch": "El notch es una pestaña o una píldora flotante que siempre sigue al dock.",
    "overhaul.fixedHint": "Siempre a mano. Nunca se oculta.",
    "mon.primary": "Principal",
    "nav.label": "Secciones de Ajustes",
    "home.appsHint": "Apps, carpetas, archivos y sitios web",
    "home.widgetsHint": "Reloj, sistema, música, notas y más",
    "home.dockHint": "Comportamiento, posición y aspecto",
    "dock.pageHint": "Cómo se comporta, dónde vive y cómo se ve.",
    "dock.behavior": "Comportamiento",
    "dock.intensity": "Intensidad del vidrio",
    "dock.intensityHint": "De transparente a esmerilado",
    "dock.interactionHint": "Zoom, etiquetas, indicadores y barra de tareas",
    "widgets.time": "Tiempo",
    "widgets.metrics": "Qué mostrar",
    "widgets.metricsHint": "Cada métrica ocupa una celda",
    "widgets.openFromDock": "Haz clic en el widget del dock para usarlo.",
    "widgets.pick": "Elige un widget para ver cómo se ve y añadirlo.",
    "system.pageHint": "Idioma, inicio, atajos, actualizaciones, perfiles y privacidad.",
    "system.privacy": "Privacidad y datos",
    "system.open": "Abrir",
    "w.system": "Sistema",
    "w.focus": "Enfoque",
    "widget.systemDesc": "CPU, memoria, disco y red en una sola placa. Elige qué mostrar.",
    "widget.focusDesc": "Temporizador y lista de tareas, guardados solo en tu PC.",
    "focus.allDone": "Todo listo",
    "finish.title": "Acabado",
    "finish.glass": "Vidrio",
    "finish.glassHint": "Desenfoca lo que hay detrás",
    "finish.darkGlass": "Vidrio oscuro",
    "finish.darkGlassHint": "Como la barra de tareas",
    "finish.mica": "Mica",
    "finish.micaHint": "Opaco, teñido por tu fondo",
    "finish.solid": "Sólido",
    "finish.solidHint": "Sin transparencia",
    "tint.black": "Negro",
    "tint.graphite": "Grafito",
    "tint.slate": "Pizarra",
    "tint.night": "Azul noche",
    "tint.white": "Blanco",
    "w.mediaIdle": "Nada sonando",
    "m.windows": "{n} ventanas",
    "hint.pickWindow": "{n} ventanas abiertas · elegir una",
    "setup.title": "Primeros pasos",
    "setup.dismiss": "Ocultar primeros pasos",
    "setup.appsTitle": "Trae tus apps",
    "setup.appsDone": "Tu dock ya tiene apps.",
    "setup.appsFrequent": "Booki encontró {n} apps que usas a menudo.",
    "setup.appsHint": "Elige las apps y carpetas que quieres tener a mano.",
    "setup.addFrequent": "Añadirlas",
    "setup.pickApps": "Elegir apps",
    "setup.startHint": "Booki aparece al encender el PC, sin abrirlo a mano.",
    "setup.startDone": "Booki se abre al iniciar Windows.",
    "setup.startOn": "Activar",
  },
  en: {
    "home.atGlance": "At a glance",
    "release81.headline": "Redesigned Settings, a notch Island that actually informs, and groups with colour and icon.",
    "release81.settings": "Home shows your dock on a desktop with an at-a-glance summary. Every section has icons, clear hierarchy and a dock preview.",
    "release81.apps": "Apps & folders, rebuilt: the dock is edited in a tidy grid and the library has tabs with large icons.",
    "release81.groups": "Groups can take a colour from a curated palette and an icon from the library, in the dock and in Settings.",
    "release81.notch": "New Island notch: a discreet dot that opens into a capsule for the timer, music or low battery.",
    "group.look": "Look",
    "group.color": "Colour",
    "group.icon": "Icon",
    "group.iconHint": "An icon replaces the grid of apps",
    "group.auto": "Automatic",
    "apps.inDock": "In your dock",
    "apps.widgetsElsewhere": "Widgets are arranged in the Widgets section",
    "apps.addTitle": "Add to the dock",
    "apps.tabApps": "Apps",
    "apps.tabFolders": "Folders",
    "apps.more": "More",
    "color.blue": "Blue",
    "color.purple": "Purple",
    "color.pink": "Pink",
    "color.red": "Red",
    "color.orange": "Orange",
    "color.yellow": "Yellow",
    "color.green": "Green",
    "color.teal": "Teal",
    "color.graphite": "Graphite",
    "color.indigo": "Indigo",
    "color.sand": "Sand",
    "notch.batteryLow": "Battery low · plug in the charger",
    "be.notchModeSmart": "Island",
    "be.notchModeSmartHint": "A quiet dot that becomes a capsule for the timer, music or a low battery.",
    "release80.headline": "Booki, rebuilt top to bottom: simpler, clearer and native to Windows 11.",
    "release80.settingsTitle": "Settings",
    "release80.settings": "Five sections instead of nine, in the style of Windows 11 Settings, on Mica. The dock preview no longer has inner scrollbars.",
    "release80.finishTitle": "Finishes",
    "release80.finish": "Glass, Mica and Solid now look truly different. The blur no longer shows as a box behind rounded corners, and widgets follow the finish.",
    "release80.widgetsTitle": "Widgets",
    "release80.widgets": "Ten widgets: System combines CPU, memory, disk and network; Focus combines timer and tasks. Your widgets convert on their own and keep their data.",
    "release80.notch": "The notch is a tab or a floating pill that always follows the dock.",
    "overhaul.fixedHint": "Always within reach. It never hides.",
    "mon.primary": "Primary",
    "nav.label": "Settings sections",
    "home.appsHint": "Apps, folders, files and websites",
    "home.widgetsHint": "Clock, system, music, notes and more",
    "home.dockHint": "Behavior, position and look",
    "dock.pageHint": "How it behaves, where it lives and how it looks.",
    "dock.behavior": "Behavior",
    "dock.intensity": "Glass intensity",
    "dock.intensityHint": "From clear to frosted",
    "dock.interactionHint": "Zoom, labels, indicators and taskbar",
    "widgets.time": "Time",
    "widgets.metrics": "What to show",
    "widgets.metricsHint": "Each metric takes one cell",
    "widgets.openFromDock": "Click the widget on the dock to use it.",
    "widgets.pick": "Pick a widget to preview it and add it.",
    "system.pageHint": "Language, startup, shortcuts, updates, profiles and privacy.",
    "system.privacy": "Privacy and data",
    "system.open": "Open",
    "w.system": "System",
    "w.focus": "Focus",
    "widget.systemDesc": "CPU, memory, disk and network on one plate. Choose what it shows.",
    "widget.focusDesc": "A timer and a task list, kept only on your PC.",
    "focus.allDone": "All done",
    "finish.title": "Finish",
    "finish.glass": "Glass",
    "finish.glassHint": "Blurs what is behind",
    "finish.darkGlass": "Dark glass",
    "finish.darkGlassHint": "Like the taskbar",
    "finish.mica": "Mica",
    "finish.micaHint": "Opaque, tinted by your wallpaper",
    "finish.solid": "Solid",
    "finish.solidHint": "No transparency",
    "tint.black": "Black",
    "tint.graphite": "Graphite",
    "tint.slate": "Slate",
    "tint.night": "Night blue",
    "tint.white": "White",
    "w.mediaIdle": "Nothing playing",
    "m.windows": "{n} windows",
    "hint.pickWindow": "{n} windows open · pick one",
    "setup.title": "Get started",
    "setup.dismiss": "Hide get started",
    "setup.appsTitle": "Bring in your apps",
    "setup.appsDone": "Your dock has apps.",
    "setup.appsFrequent": "Booki found {n} apps you use often.",
    "setup.appsHint": "Pick the apps and folders you want within reach.",
    "setup.addFrequent": "Add them",
    "setup.pickApps": "Choose apps",
    "setup.startHint": "Booki is there when your PC starts, without opening it yourself.",
    "setup.startDone": "Booki opens when Windows starts.",
    "setup.startOn": "Turn on",
  },
  pt: {
    "home.atGlance": "Num relance",
    "release81.headline": "Definições redesenhadas, uma ilha de notch que informa de verdade e grupos com cor e ícone.",
    "release81.settings": "O Início mostra o seu dock sobre um ambiente de trabalho com um resumo rápido. Cada secção tem ícones, hierarquia clara e pré-visualização do dock.",
    "release81.apps": "Apps e pastas, refeito: o dock edita-se numa grelha arrumada e a biblioteca tem separadores com ícones grandes.",
    "release81.groups": "Os grupos podem ter uma cor de uma paleta cuidada e um ícone da biblioteca, no dock e nas Definições.",
    "release81.notch": "Novo notch Ilha: um ponto discreto que se abre numa cápsula com o temporizador, a música ou a bateria fraca.",
    "group.look": "Aparência",
    "group.color": "Cor",
    "group.icon": "Ícone",
    "group.iconHint": "Um ícone substitui a grelha de apps",
    "group.auto": "Automático",
    "apps.inDock": "No seu dock",
    "apps.widgetsElsewhere": "Os widgets organizam-se na secção Widgets",
    "apps.addTitle": "Adicionar ao dock",
    "apps.tabApps": "Apps",
    "apps.tabFolders": "Pastas",
    "apps.more": "Mais",
    "color.blue": "Azul",
    "color.purple": "Roxo",
    "color.pink": "Rosa",
    "color.red": "Vermelho",
    "color.orange": "Laranja",
    "color.yellow": "Amarelo",
    "color.green": "Verde",
    "color.teal": "Turquesa",
    "color.graphite": "Grafite",
    "color.indigo": "Índigo",
    "color.sand": "Areia",
    "notch.batteryLow": "Bateria fraca · ligue o carregador",
    "be.notchModeSmart": "Ilha",
    "be.notchModeSmartHint": "Um ponto discreto que vira cápsula com o temporizador, a música ou a bateria fraca.",
    "release80.headline": "Booki, refeito de cima a baixo: mais simples, mais claro e nativo do Windows 11.",
    "release80.settingsTitle": "Definições",
    "release80.settings": "Cinco secções em vez de nove, ao estilo das Definições do Windows 11, sobre Mica. A pré-visualização do dock já não tem barras de deslocamento internas.",
    "release80.finishTitle": "Acabamentos",
    "release80.finish": "Vidro, Mica e Sólido agora parecem mesmo diferentes. O desfoque já não aparece como uma caixa atrás dos cantos arredondados e os widgets seguem o acabamento.",
    "release80.widgetsTitle": "Widgets",
    "release80.widgets": "Dez widgets: Sistema junta CPU, memória, disco e rede; Foco junta temporizador e tarefas. Os seus widgets convertem-se sozinhos e mantêm os dados.",
    "release80.notch": "O notch é uma aba ou uma pílula flutuante que segue sempre o dock.",
    "overhaul.fixedHint": "Sempre à mão. Nunca se esconde.",
    "mon.primary": "Principal",
    "nav.label": "Secções das definições",
    "home.appsHint": "Apps, pastas, ficheiros e sites",
    "home.widgetsHint": "Relógio, sistema, música, notas e mais",
    "home.dockHint": "Comportamento, posição e aspeto",
    "dock.pageHint": "Como se comporta, onde fica e como aparece.",
    "dock.behavior": "Comportamento",
    "dock.intensity": "Intensidade do vidro",
    "dock.intensityHint": "De transparente a fosco",
    "dock.interactionHint": "Zoom, etiquetas, indicadores e barra de tarefas",
    "widgets.time": "Tempo",
    "widgets.metrics": "O que mostrar",
    "widgets.metricsHint": "Cada métrica ocupa uma célula",
    "widgets.openFromDock": "Clique no widget no dock para usá-lo.",
    "widgets.pick": "Escolha um widget para o ver e adicionar.",
    "system.pageHint": "Idioma, arranque, atalhos, atualizações, perfis e privacidade.",
    "system.privacy": "Privacidade e dados",
    "system.open": "Abrir",
    "w.system": "Sistema",
    "w.focus": "Foco",
    "widget.systemDesc": "CPU, memória, disco e rede numa só placa. Escolha o que mostrar.",
    "widget.focusDesc": "Um temporizador e uma lista de tarefas, guardados só no seu PC.",
    "focus.allDone": "Tudo feito",
    "finish.title": "Acabamento",
    "finish.glass": "Vidro",
    "finish.glassHint": "Desfoca o que está atrás",
    "finish.darkGlass": "Vidro escuro",
    "finish.darkGlassHint": "Como a barra de tarefas",
    "finish.mica": "Mica",
    "finish.micaHint": "Opaco, tingido pelo seu papel de parede",
    "finish.solid": "Sólido",
    "finish.solidHint": "Sem transparência",
    "tint.black": "Preto",
    "tint.graphite": "Grafite",
    "tint.slate": "Ardósia",
    "tint.night": "Azul-noite",
    "tint.white": "Branco",
    "w.mediaIdle": "Nada a tocar",
    "m.windows": "{n} janelas",
    "hint.pickWindow": "{n} janelas abertas · escolher uma",
    "setup.title": "Primeiros passos",
    "setup.dismiss": "Ocultar primeiros passos",
    "setup.appsTitle": "Traga as suas apps",
    "setup.appsDone": "O seu dock já tem apps.",
    "setup.appsFrequent": "O Booki encontrou {n} apps que usa com frequência.",
    "setup.appsHint": "Escolha as apps e pastas que quer ter à mão.",
    "setup.addFrequent": "Adicioná-las",
    "setup.pickApps": "Escolher apps",
    "setup.startHint": "O Booki aparece quando liga o PC, sem o abrir à mão.",
    "setup.startDone": "O Booki abre ao iniciar o Windows.",
    "setup.startOn": "Ativar",
  },
  fr: {
    "home.atGlance": "En un coup d’œil",
    "release81.headline": "Réglages repensés, une île de notch vraiment utile et des groupes avec couleur et icône.",
    "release81.settings": "L’accueil montre votre dock sur un bureau avec un résumé en un coup d’œil. Chaque section a des icônes, une hiérarchie claire et un aperçu du dock.",
    "release81.apps": "Apps et dossiers, refait : le dock s’édite dans une grille ordonnée et la bibliothèque a des onglets aux grandes icônes.",
    "release81.groups": "Les groupes peuvent prendre une couleur d’une palette soignée et une icône de la bibliothèque, dans le dock et les Réglages.",
    "release81.notch": "Nouveau notch Île : un point discret qui s’ouvre en capsule pour le minuteur, la musique ou la batterie faible.",
    "group.look": "Apparence",
    "group.color": "Couleur",
    "group.icon": "Icône",
    "group.iconHint": "Une icône remplace la grille d’apps",
    "group.auto": "Automatique",
    "apps.inDock": "Dans votre dock",
    "apps.widgetsElsewhere": "Les widgets s’organisent dans la section Widgets",
    "apps.addTitle": "Ajouter au dock",
    "apps.tabApps": "Apps",
    "apps.tabFolders": "Dossiers",
    "apps.more": "Plus",
    "color.blue": "Bleu",
    "color.purple": "Violet",
    "color.pink": "Rose",
    "color.red": "Rouge",
    "color.orange": "Orange",
    "color.yellow": "Jaune",
    "color.green": "Vert",
    "color.teal": "Turquoise",
    "color.graphite": "Graphite",
    "color.indigo": "Indigo",
    "color.sand": "Sable",
    "notch.batteryLow": "Batterie faible · branchez le chargeur",
    "be.notchModeSmart": "Îlot",
    "be.notchModeSmartHint": "Un point discret qui devient une capsule pour le minuteur, la musique ou une batterie faible.",
    "release80.headline": "Booki, reconstruit de fond en comble : plus simple, plus clair et natif de Windows 11.",
    "release80.settingsTitle": "Paramètres",
    "release80.settings": "Cinq sections au lieu de neuf, dans le style des Paramètres de Windows 11, sur Mica. L’aperçu du dock n’a plus de barres de défilement internes.",
    "release80.finishTitle": "Finitions",
    "release80.finish": "Verre, Mica et Opaque sont désormais vraiment différents. Le flou n’apparaît plus comme un cadre derrière les coins arrondis, et les widgets suivent la finition.",
    "release80.widgetsTitle": "Widgets",
    "release80.widgets": "Dix widgets : Système regroupe processeur, mémoire, disque et réseau ; Concentration regroupe minuteur et tâches. Vos widgets se convertissent seuls et gardent leurs données.",
    "release80.notch": "Le notch est un onglet ou une pilule flottante qui suit toujours le dock.",
    "overhaul.fixedHint": "Toujours à portée de main. Il ne se masque jamais.",
    "mon.primary": "Principal",
    "nav.label": "Sections des paramètres",
    "home.appsHint": "Applis, dossiers, fichiers et sites web",
    "home.widgetsHint": "Horloge, système, musique, notes et plus",
    "home.dockHint": "Comportement, position et apparence",
    "dock.pageHint": "Son comportement, sa place et son apparence.",
    "dock.behavior": "Comportement",
    "dock.intensity": "Intensité du verre",
    "dock.intensityHint": "De transparent à dépoli",
    "dock.interactionHint": "Zoom, étiquettes, indicateurs et barre des tâches",
    "widgets.time": "Temps",
    "widgets.metrics": "Quoi afficher",
    "widgets.metricsHint": "Chaque mesure occupe une case",
    "widgets.openFromDock": "Cliquez sur le widget dans le dock pour l’utiliser.",
    "widgets.pick": "Choisissez un widget pour l’aperçu et l’ajout.",
    "system.pageHint": "Langue, démarrage, raccourcis, mises à jour, profils et confidentialité.",
    "system.privacy": "Confidentialité et données",
    "system.open": "Ouvrir",
    "w.system": "Système",
    "w.focus": "Concentration",
    "widget.systemDesc": "Processeur, mémoire, disque et réseau sur une seule plaque. Choisissez quoi afficher.",
    "widget.focusDesc": "Un minuteur et une liste de tâches, gardés uniquement sur votre PC.",
    "focus.allDone": "Tout est fait",
    "finish.title": "Finition",
    "finish.glass": "Verre",
    "finish.glassHint": "Floute ce qui est derrière",
    "finish.darkGlass": "Verre sombre",
    "finish.darkGlassHint": "Comme la barre des tâches",
    "finish.mica": "Mica",
    "finish.micaHint": "Opaque, teinté par votre fond d’écran",
    "finish.solid": "Opaque",
    "finish.solidHint": "Sans transparence",
    "tint.black": "Noir",
    "tint.graphite": "Graphite",
    "tint.slate": "Ardoise",
    "tint.night": "Bleu nuit",
    "tint.white": "Blanc",
    "w.mediaIdle": "Rien en lecture",
    "m.windows": "{n} fenêtres",
    "hint.pickWindow": "{n} fenêtres ouvertes · en choisir une",
    "setup.title": "Premiers pas",
    "setup.dismiss": "Masquer les premiers pas",
    "setup.appsTitle": "Ajoutez vos apps",
    "setup.appsDone": "Votre dock a des apps.",
    "setup.appsFrequent": "Booki a trouvé {n} apps que vous utilisez souvent.",
    "setup.appsHint": "Choisissez les apps et dossiers à garder sous la main.",
    "setup.addFrequent": "Les ajouter",
    "setup.pickApps": "Choisir des apps",
    "setup.startHint": "Booki est là dès le démarrage du PC, sans l'ouvrir vous-même.",
    "setup.startDone": "Booki s'ouvre au démarrage de Windows.",
    "setup.startOn": "Activer",
  },
  de: {
    "home.atGlance": "Auf einen Blick",
    "release81.headline": "Neu gestaltete Einstellungen, eine Notch-Insel mit echten Infos und Gruppen mit Farbe und Symbol.",
    "release81.settings": "Start zeigt dein Dock auf einem Desktop mit Überblick. Jeder Bereich hat Symbole, klare Hierarchie und eine Dock-Vorschau.",
    "release81.apps": "Apps & Ordner, neu gebaut: Das Dock wird in einem ordentlichen Raster bearbeitet, die Bibliothek hat Tabs mit großen Symbolen.",
    "release81.groups": "Gruppen bekommen eine Farbe aus einer kuratierten Palette und ein Symbol aus der Bibliothek, im Dock und in den Einstellungen.",
    "release81.notch": "Neue Insel-Notch: ein dezenter Punkt, der sich für Timer, Musik oder schwachen Akku zur Kapsel öffnet.",
    "group.look": "Aussehen",
    "group.color": "Farbe",
    "group.icon": "Symbol",
    "group.iconHint": "Ein Symbol ersetzt das App-Raster",
    "group.auto": "Automatisch",
    "apps.inDock": "In deinem Dock",
    "apps.widgetsElsewhere": "Widgets ordnest du im Bereich Widgets",
    "apps.addTitle": "Zum Dock hinzufügen",
    "apps.tabApps": "Apps",
    "apps.tabFolders": "Ordner",
    "apps.more": "Mehr",
    "color.blue": "Blau",
    "color.purple": "Lila",
    "color.pink": "Pink",
    "color.red": "Rot",
    "color.orange": "Orange",
    "color.yellow": "Gelb",
    "color.green": "Grün",
    "color.teal": "Türkis",
    "color.graphite": "Graphit",
    "color.indigo": "Indigo",
    "color.sand": "Sand",
    "notch.batteryLow": "Akku schwach · Ladegerät anschließen",
    "be.notchModeSmart": "Insel",
    "be.notchModeSmartHint": "Ein dezenter Punkt, der für Timer, Musik oder schwachen Akku zur Kapsel wird.",
    "release80.headline": "Booki, von Grund auf neu gebaut: einfacher, klarer und nativ für Windows 11.",
    "release80.settingsTitle": "Einstellungen",
    "release80.settings": "Fünf statt neun Bereiche, im Stil der Windows-11-Einstellungen, auf Mica. Die Dock-Vorschau hat keine inneren Bildlaufleisten mehr.",
    "release80.finishTitle": "Oberflächen",
    "release80.finish": "Glas, Mica und Deckend sehen jetzt wirklich verschieden aus. Die Unschärfe erscheint nicht mehr als Kasten hinter runden Ecken, und Widgets folgen der Oberfläche.",
    "release80.widgetsTitle": "Widgets",
    "release80.widgets": "Zehn Widgets: System vereint CPU, Arbeitsspeicher, Datenträger und Netzwerk; Fokus vereint Timer und Aufgaben. Deine Widgets werden automatisch umgestellt und behalten ihre Daten.",
    "release80.notch": "Der Notch ist ein Reiter oder eine schwebende Pille, die immer dem Dock folgt.",
    "overhaul.fixedHint": "Immer griffbereit. Es blendet sich nie aus.",
    "mon.primary": "Hauptbildschirm",
    "nav.label": "Einstellungsbereiche",
    "home.appsHint": "Apps, Ordner, Dateien und Websites",
    "home.widgetsHint": "Uhr, System, Musik, Notizen und mehr",
    "home.dockHint": "Verhalten, Position und Aussehen",
    "dock.pageHint": "Wie es sich verhält, wo es sitzt und wie es aussieht.",
    "dock.behavior": "Verhalten",
    "dock.intensity": "Glasintensität",
    "dock.intensityHint": "Von klar bis milchig",
    "dock.interactionHint": "Zoom, Beschriftungen, Anzeigen und Taskleiste",
    "widgets.time": "Zeit",
    "widgets.metrics": "Was angezeigt wird",
    "widgets.metricsHint": "Jeder Wert belegt eine Zelle",
    "widgets.openFromDock": "Klicke im Dock auf das Widget, um es zu benutzen.",
    "widgets.pick": "Wähle ein Widget für Vorschau und Hinzufügen.",
    "system.pageHint": "Sprache, Autostart, Tastenkürzel, Updates, Profile und Datenschutz.",
    "system.privacy": "Datenschutz und Daten",
    "system.open": "Öffnen",
    "w.system": "System",
    "w.focus": "Fokus",
    "widget.systemDesc": "CPU, Arbeitsspeicher, Datenträger und Netzwerk auf einer Kachel. Wähle, was sie zeigt.",
    "widget.focusDesc": "Ein Timer und eine Aufgabenliste, nur auf deinem PC gespeichert.",
    "focus.allDone": "Alles erledigt",
    "finish.title": "Oberfläche",
    "finish.glass": "Glas",
    "finish.glassHint": "Macht den Hintergrund unscharf",
    "finish.darkGlass": "Dunkles Glas",
    "finish.darkGlassHint": "Wie die Taskleiste",
    "finish.mica": "Mica",
    "finish.micaHint": "Deckend, vom Hintergrundbild getönt",
    "finish.solid": "Deckend",
    "finish.solidHint": "Keine Transparenz",
    "tint.black": "Schwarz",
    "tint.graphite": "Graphit",
    "tint.slate": "Schiefer",
    "tint.night": "Nachtblau",
    "tint.white": "Weiß",
    "w.mediaIdle": "Keine Wiedergabe",
    "m.windows": "{n} Fenster",
    "hint.pickWindow": "{n} Fenster offen · eins wählen",
    "setup.title": "Erste Schritte",
    "setup.dismiss": "Erste Schritte ausblenden",
    "setup.appsTitle": "Deine Apps holen",
    "setup.appsDone": "Dein Dock hat Apps.",
    "setup.appsFrequent": "Booki hat {n} Apps gefunden, die du oft nutzt.",
    "setup.appsHint": "Wähle die Apps und Ordner, die du griffbereit haben willst.",
    "setup.addFrequent": "Hinzufügen",
    "setup.pickApps": "Apps wählen",
    "setup.startHint": "Booki ist da, sobald der PC startet, ohne es selbst zu öffnen.",
    "setup.startDone": "Booki öffnet sich beim Start von Windows.",
    "setup.startOn": "Einschalten",
  },
};
